import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, ArrowUpRight, ChevronDown, CircleHelp, Clapperboard, Database, Github, Layers3, Search, Sparkles, Star, Users, X} from 'lucide-react';
import './style.css';

const EXAMPLES = [1, 42, 100, 256, 481];
function App() {
  const [profiles, setProfiles] = useState(null);
  const [metrics, setMetrics] = useState(null);
  const [selected, setSelected] = useState(1);
  const [input, setInput] = useState('1');
  const [error, setError] = useState('');
  const [showMethod, setShowMethod] = useState(false);
  const [query, setQuery] = useState('');
  useEffect(() => {
    Promise.all([fetch('/recommendations.json').then(r => {if (!r.ok) throw Error('Recommendations unavailable'); return r.json()}), fetch('/metrics.json').then(r => {if (!r.ok) throw Error('Metrics unavailable'); return r.json()})])
      .then(([p, m]) => {setProfiles(p); setMetrics(m)})
      .catch(() => setError('Could not load recommendation data. Please refresh the page.'));
  }, []);
  function select(id) {
    const numeric = Number(id);
    if (!Number.isInteger(numeric) || !profiles?.[numeric]) {setError('Choose a user ID between 1 and 610.'); return}
    setSelected(numeric); setInput(String(numeric)); setQuery(''); setError('');
  }
  const profile = profiles?.[selected];
  const shown = profile?.recommendations.filter(movie => (movie.title + movie.genres.join(' ')).toLowerCase().includes(query.toLowerCase())) || [];
  return <div className="app">
    <header className="nav wrap"><a className="brand" href="#top" aria-label="Echo home"><span className="brand-icon"><Layers3 size={21}/></span><span>echo<span className="brand-period">.</span></span></a><nav><a href="#explore">Explore</a><a href="#how">How it works</a><a href="#results">Model results</a></nav><a className="nav-github" href="https://github.com/mizerolucky/DS_7_EchoRecommendationEngine_BYTE" target="_blank" rel="noreferrer"><Github size={16}/> View on GitHub <ArrowUpRight size={14}/></a></header>
    <main id="top"><section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> A DATA SCIENCE PROJECT <span className="eyebrow-rule"/> TASK 07</div><h1>Great movies.<br/><em>Found for you.</em></h1><p className="hero-sub">A recommendation engine that learns patterns from real movie ratings to uncover what each viewer might love next.</p><a className="primary-cta" href="#explore">Explore recommendations <ArrowRight size={18}/></a><div className="hero-caption"><span className="small-asterisk">✳</span> Built on MovieLens data. Powered by matrix factorization.</div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-1"/><div className="orbit orbit-2"/><div className="orbit orbit-3"/><div className="orbit-core"><Sparkles size={38} strokeWidth={1.3}/><span>YOUR NEXT<br/>FAVORITE</span></div><div className="orbit-item item-one"><Clapperboard size={22}/></div><div className="orbit-item item-two"><Star size={22}/></div><div className="orbit-item item-three"><Sparkles size={22}/></div><div className="orbit-item item-four"><Clapperboard size={22}/></div><div className="art-grain"/></div></section>
    <section className="stat-strip"><div className="wrap stat-inner"><div><strong>{metrics ? metrics.counts.users.toLocaleString() : '—'}</strong><span>viewer profiles</span></div><i/><div><strong>{metrics ? metrics.counts.movies.toLocaleString() : '—'}</strong><span>movies in catalog</span></div><i/><div><strong>{metrics ? (metrics.counts.train+metrics.counts.validation+metrics.counts.test).toLocaleString() : '—'}</strong><span>real ratings analyzed</span></div><i/><div><strong>{metrics ? metrics.test_model.rmse.toFixed(3) : '—'}</strong><span>test RMSE ↓</span></div></div></section>
    <section className="explore wrap" id="explore"><div className="section-heading"><div><div className="section-kicker">01 / EXPLORE</div><h2>Find a viewer's <em>next favorite.</em></h2><p>Pick a MovieLens viewer profile to see its five highest rated unseen movies.</p></div><span className="section-mark"><Sparkles size={25}/></span></div><div className="explore-grid"><aside className="control-panel"><div className="panel-label"><Users size={17}/> VIEWER PROFILE</div><p className="panel-intro">Each ID represents an anonymous viewer with a history of real movie ratings.</p><label htmlFor="user-id">Enter a user ID</label><form onSubmit={e=>{e.preventDefault();select(input)}} className="id-form"><input id="user-id" type="number" min="1" max="610" value={input} onChange={e=>setInput(e.target.value)} placeholder="1 – 610"/><button type="submit" aria-label="Get recommendations"><ArrowRight size={18}/></button></form><div className="divider"><span>OR TRY AN EXAMPLE</span></div><div className="example-grid">{EXAMPLES.map(id=><button className={'chip '+(selected===id?'active':'')} key={id} onClick={()=>select(id)}>User {id}</button>)}</div>{error && <p className="error" role="alert">{error}</p>}<div className="panel-note"><CircleHelp size={16}/><span>These are anonymous dataset IDs, not accounts. Recommendations are generated from training ratings only.</span></div></aside><div className="results-panel"><div className="results-top"><div><span className="results-label">PERSONALIZED SELECTION</span><h3>For viewer <span>#{selected}</span></h3><p>{profile ? `${profile.ratedCount} known ratings shaped this profile` : 'Loading recommendations…'}</p></div><div className="result-icon"><Sparkles size={19}/></div></div><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Filter recommendations" placeholder="Filter these recommendations…"/></div><div className="movie-list">{shown.map((movie,i)=><article className="movie" key={movie.movieId}><div className="movie-index">{String(i+1).padStart(2,'0')}</div><div className="movie-icon"><Clapperboard size={22}/></div><div className="movie-copy"><h4>{movie.title}</h4><p>{movie.genres.filter(x=>x!=='(no genres listed)').slice(0,3).join(' · ') || 'Uncategorized'}</p></div><div className="movie-score"><Star size={15} fill="currentColor"/><strong>{movie.score.toFixed(2)}</strong><small>/ 5 predicted</small></div></article>)}{profile && shown.length===0 && <div className="empty">No recommendations match that filter.</div>}</div><div className="result-foot"><span><span className="foot-dot"/> Previously rated titles excluded</span><span>Top 5 predicted ratings</span></div></div></div></section>
    <section className="method" id="how"><div className="wrap method-inner"><div className="method-copy"><div className="section-kicker">02 / THE APPROACH</div><h2>Finding patterns <em>between the ratings.</em></h2><p>People who rate movies similarly often share hidden preferences. Echo transforms a sparse viewer–movie rating matrix into compact factors that capture those patterns.</p><button className="text-button" onClick={()=>setShowMethod(!showMethod)} aria-expanded={showMethod}>{showMethod?'Hide methodology':'Read the methodology'} {showMethod?<X size={16}/>:<ArrowRight size={16}/>}</button></div><div className="steps"><div className="step"><span>01</span><div><Database size={19}/><h3>Prepare</h3><p>Split ratings per user into training, validation, and untouched test sets.</p></div></div><div className="step"><span>02</span><div><Layers3 size={19}/><h3>Learn</h3><p>Fit regularized user and movie biases, then factorize the sparse residual matrix using truncated SVD.</p></div></div><div className="step"><span>03</span><div><Sparkles size={19}/><h3>Recommend</h3><p>Score unseen movies and return the five highest predictions for each viewer.</p></div></div></div></div>{showMethod&&<div className="wrap method-extra"><strong>What the score means</strong><p>The displayed value is a predicted rating on a 0.5–5 scale, not the probability someone will watch or like a film. We tune factor count and shrinkage using validation RMSE. The final test ratings are held aside until the end; the demo shows recommendations generated from the training and validation data. New users need rating history before collaborative filtering can personalize their results.</p></div>}</section>
    <section className="evaluation wrap" id="results"><div className="section-kicker">03 / EVALUATION</div><div className="evaluation-header"><h2>Measured on <em>unseen ratings.</em></h2><p>Held-out ratings tell us how closely the model predicts real viewer scores. Lower error is better.</p></div><div className="metric-grid"><div className="metric-card"><div className="metric-label">TEST RMSE <span>↓</span></div><strong>{metrics?.test_model.rmse.toFixed(4)??'—'}</strong><p>Root mean squared error · matrix factorization</p></div><div className="metric-card"><div className="metric-label">TEST MAE <span>↓</span></div><strong>{metrics?.test_model.mae.toFixed(4)??'—'}</strong><p>Mean absolute error · matrix factorization</p></div><div className="metric-card baseline-card"><div className="metric-label">BIAS-ONLY BASELINE</div><strong>{metrics?.test_baseline.rmse.toFixed(4)??'—'}</strong><p>Test RMSE without latent factors</p></div></div><div className="eval-note"><CircleHelp size={17}/><span>Prediction error measures rating accuracy. It does not establish recommendation quality, diversity, or real-world engagement.</span></div></section></main>
    <footer><div className="wrap footer-inner"><div className="brand footer-brand"><span className="brand-icon"><Layers3 size={19}/></span><span>echo<span className="brand-period">.</span></span></div><p>Movie discovery through data science. <span>MovieLens data by GroupLens Research.</span></p><a href="https://grouplens.org/datasets/movielens/latest/" target="_blank" rel="noreferrer">Dataset source <ArrowUpRight size={14}/></a></div></footer>
  </div>;
}

createRoot(document.getElementById('root')).render(<App/>);
